/*
 * Copyright Amadeus
 */
(function(){var g={},e=null,n=null,p=-1,u=function(){var a=aria.ext.StressCss;a.original__load=aria.templates.CSSMgr.__load;a.original__unload=aria.templates.CSSMgr.__unload;aria.templates.CSSMgr.__load=function(){return[]};aria.templates.CSSMgr.__unload=function(){};k()},v=function(a,b){for(var c=null,d=[],f=aria.utils.String.trim,l=/[\s]*(([^{]+)\{[^}]+\})/g;c=l.exec(a);)d.push({name:b+": "+f(c[2]),descriptor:c[1],location:b});return d},w=function(a,b){if(a){aria.templates.CSSMgr.__textLoaded[a.location].text=
a.original;k()}else b&&k()},k=function(a,b){if(a!==true)aria.templates.CSSMgr.__textToDOM(aria.utils.Object.keys(aria.templates.CSSMgr.__styleTagPool));else{var c={},d;for(d in aria.templates.CSSMgr.__styleTagPool)if(aria.templates.CSSMgr.__styleTagPool.hasOwnProperty(d))c[d]=d==="tpl"&&b?[b]:[];aria.templates.CSSMgr.__reloadStyleTags(c)}},x=function(a){a.runTime=+new Date-a.start;g[a.name]={name:a.name,runTime:a.runTime,baseline:g.__baseline__?g.__baseline__.runTime-a.runTime:NaN};w(a.selector,a.cfg.incremental);
setTimeout(function(){a.callback&&a.callback.fn.apply(a.callback.scope,a.callback.args)},15)},q=function(a){if(a.iteration>=a.cfg.repeat)return x(a);a.iteration+=1;a.cfg.action.call(null,a.name,a.iteration-1,y(a,this))},y=function(a,b){return function(){setTimeout(function(){q.call(b,a)},0)}},r=function(a){a.iteration=0;var b=a.selector,c=a.cfg.incremental;if(b){var d=aria.templates.CSSMgr.__textLoaded[b.location];b.original=d.text;if(c)k(true,b.descriptor);else{d.text=d.text.replace(b.descriptor,
"");k()}}else c&&k(true);b=!(a.selector&&a.selector.name!=="*");if(n){c=a.cfg.allSelectors.length;n.innerHTML="Testing <strong>"+(b?a.name:a.selector.name)+"</strong>"+("<br />"+(b?"baseline":a.selector.location))+("<br />"+c+" remaining test"+(c===1?"":"s"))}a.start=+new Date;q(a)},z=function(a,b){g={};r({name:"__baseline__",cfg:a,selector:null,callback:{fn:s,scope:this,args:[a,b]}})},s=function(a,b){if(a.allSelectors.length>0){var c=a.allSelectors.splice(0,1)[0];r({name:c.name,cfg:a,selector:c,
callback:{fn:s,scope:this,args:[a,b]}})}else{A(a.incremental);aria.ext.StressCss.__callback(b)}},m=function(a,b){for(var c in b)if(b.hasOwnProperty(c))try{var d=c.replace(/\-([a-z])/ig,function(h,i){return i.toUpperCase()}),f=b[c];a.style[d]=typeof f=="number"&&d!="zIndex"?f+"px":f}catch(l){}},t=function(){if(e){e.parentNode.removeChild(e);e=null;return false}},B=function(){var a=Aria.$window.document;e=a.createElement("iframe");var b=a.createElement("iframe");e.scrolling="no";e.frameBorder="no";
a.body.appendChild(e);e.doc=e.contentDocument||e.contentWindow.document;e.doc.write("<html><head></head><body></body></html>");e.doc.close();n=e.doc.createElement("div");var c=e.doc.createElement("a");e.resize=function(){if(e){var d=e.doc.body;m(e,{width:d.scrollWidth,height:d.scrollHeight})}};p=setInterval(e.resize,100);m(e,{position:"fixed",top:10,right:10,zIndex:1E4,background:"white",padding:2,border:"solid 2px #aaa",width:250,height:60,borderRadius:4,boxShadow:"0 0 8px #eee"});m(e.doc.body,{font:"12px Helvetica,Arials,sans-serif",
color:"#444"});m(n,{whiteSpace:"nowrap"});c.innerHTML="&#215;";m(c,{position:"absolute",top:0,right:0,textDecoration:"none",fontWeight:"bold",cursor:"pointer",color:"red",fontSize:"1.3em",lineHeight:8});c.onclick=function(){c.onclick=null;clearInterval(p);c=null;b.parentNode.removeChild(b);return t()};m(b,{height:Aria.$window.screen.height*2,width:Aria.$window.screen.width,position:"absolute",top:0,left:0,visible:"hidden",display:"none",zIndex:0});a.body.appendChild(b);e.doc.body.appendChild(c);e.doc.body.appendChild(n)},
A=function(a){if(e&&g){var b="<table><thead><tr><th>Selector</th><th> </th><th>ms</th><th>Total</th></tr></thead><tbody>",c=[],d;for(d in g)g.hasOwnProperty(d)&&d!=="__baseline__"&&c.push(g[d]);d=c.sort(function(i,j){if(i.baseline===j.baseline)return 0;return a?i.baseline>j.baseline?1:-1:i.baseline>j.baseline?-1:1}).slice(0,20);for(var f=0,l=d.length;f<l;f+=1){var h=d[f];b+='<tr><td style="font:11px monospace">Removing <strong>'+h.name+'</strong></td><td style="text-align:right">'+(h.baseline>0?'<span style="color:green">saves</span>':
'<span style="color:red">adds</span>')+'</td><td style="text-align:right; font:11px monospace">'+Math.abs(h.baseline)+'ms</td><td style="text-align:right; font:11px monospace">'+h.runTime+"ms</td></tr>\n"}b+="</tbody></table><hr/>";b+='<table><tr><td style="text-align:right; font:10px monospace">Selectors Tested:</td><td style="font:10px monospace">'+c.length+'</td></tr><tr><td style="text-align:right; font:10px monospace">Baseline Time:</td><td style="font:10px monospace">'+g.__baseline__.runTime+
"ms</td></tr>";m(e,{width:600});n.innerHTML=b}},o={repeat:2,silent:false,widget:false,action:function(a,b,c){a=0;for(b=Aria.rootTemplates.length;a<b;a+=1)Aria.rootTemplates[a].$refresh();c()},incremental:false};Aria.classDefinition({$classpath:"aria.ext.StressCss",$constructor:function(){},$singleton:true,$dependencies:["aria.utils.Object","aria.utils.String"],$prototype:{stressTest:function(a,b){u();var c;c=a||{};for(var d in o)if(o.hasOwnProperty(d)&&!(d in c))c[d]=o[d];d=c;var f=c.widget,l=aria.templates.CSSMgr,
h=l.__textLoaded,i=[],j;for(j in h)if(h.hasOwnProperty(j))f!==true&&l.__styleTagAssociation[j]==="wgt"||(i=i.concat(v(h[j].text,j)));d.allSelectors=i;a=c;t();a.silent||B();z(a,b)},getResults:function(){return g},__callback:function(a){var b=aria.ext.StressCss;aria.templates.CSSMgr.__load=b.original__load;aria.templates.CSSMgr.__unload=b.original__unload;k();this.$callback(a)}}})})();