/*
 * Copyright Amadeus
 */
//***MULTI-PART
//AISBa0GIBM
//LOGICAL-PATH:aria/resources/handlers/AIRResourcesHandler.js
//AISBa0GIBM
(function(){var t,u,s;Aria.classDefinition({$classpath:"aria.resources.handlers.AIRResourcesHandler",$dependencies:["aria.core.DownloadMgr","aria.utils.String","aria.resources.handlers.AIRResourcesHandlerBean","aria.core.environment.Environment"],$constructor:function(){this.threshold=3},$destructor:function(){},$statics:{SUGGESTION_BEAN:"aria.resources.handlers.AIRResourcesHandlerBean.Suggestion",LATIN_CHAR_REGEXP:/^[a-z]/i},$onload:function(){t=aria.core.DownloadMgr;u=aria.core.environment.Environment;
s=aria.utils.String},$onunload:function(){s=u=t=null},$prototype:{getSuggestions:function(a,d){var c=false,b;if(a){b=a.charAt(0).toUpperCase();c=true;if(!this.LATIN_CHAR_REGEXP.test(b)){b=b.charCodeAt(0);if(b<128)c=false}}if(c){c=u.getRegion();a=s.stripAccents(a).toLowerCase();b=Aria.FRAMEWORK_RESOURCES+"AIR/"+c+"/"+b+".txt";t.loadFile(b,{fn:this._onResourceReceive,scope:this,args:{textEntry:a,callback:d,logicalPath:b}})}else this.$callback(d,null)},getDefaultTemplate:function(){return"aria.widgets.form.list.templates.AIRList"},
_onResourceReceive:function(a,d){var c=d.textEntry,b=d.callback;if(a.downloadFailed)this.$callback(b,null);else{var e=aria.core.DownloadMgr.getFileContent(d.logicalPath);c=this._getSuggestions(c,e);this.$callback(b,c)}},_getSuggestions:function(a,d){if(a.length<this.threshold)return null;if(d==null)return[];a=decodeURIComponent(a);var c=[];if(a.length<4){var b="#"+a.toUpperCase();this._searchSuggestion(d,b,c)}if(a.length==3){b=0;for(var e=c.length;b<e;b++)c[b].exactMatch=true}b=",";e=true;for(var g=
0;g<a.length;g++){if(e){e=false;b+=a.charAt(g).toUpperCase()}else b+=a.charAt(g).toLowerCase();if(a.charAt(g)==" ")e=true}this._searchSuggestion(d,b,c);return c},_getNbOfIATAAirportsInMultiCity:function(a,d){var c=a.substring(d+1,a.indexOf(",",d));return c==""||isNaN(c)?0:parseInt(c)},_searchSuggestion:function(a,d,c){var b,e,g,h,f,i,m=a;a=s.stripAccents(a);for(var k=a.indexOf(d);k!=-1;){f=a.lastIndexOf("[",k)+1;var j=a.substr(f,2),q=this._getCountryName(m,f+2),l=a.lastIndexOf("]",k)+1,r="",o="";
if(l!=-1&&l>f){r=a.substr(l,2);o=a.indexOf("#",l);o=a.substring(l+2,o)}h=a.lastIndexOf("#",k)+1;f=a.substr(h,3);l=a.indexOf(",",h)+1;b=this._getCityName(m,l);l=b.name;if(b.stateCode!="")r=b.stateCode;if(b.stateName!="")o=b.stateName;if(b.countryCode!="")j=b.countryCode;if(b.countryName!="")q=b.countryName;h+=3;i=a.charAt(h);if(i==="{"){this._addSuggestion(c,1,f,l,null,r,o,j,q);i=this._getNbOfIATAAirportsInMultiCity(a,h);for(var n=0;n<i;n++){var p=a.indexOf("#",h)+1,v=a.substr(p,3);p+=5;b=this._getCityName(a,
p);f=b.name;e=b.stateCode!=""?b.stateCode:r;g=b.stateName!=""?b.stateName:o;h=b.countryCode!=""?b.countryCode:j;b=b.countryName!=""?b.countryName:q;this._addSuggestion(c,2,v,l,f,e,g,h,b);h=a.indexOf("#",p)}}else if(i===")"){e=a.lastIndexOf("{",h);g=a.lastIndexOf("+",h);i=a.lastIndexOf("-",h);if(i>g)g=i;if(g>e)e=g;e=a.indexOf(",",e)+1;b=this._getCityName(m,e);i=b.name;e=b.stateCode!=""?b.stateCode:r;g=b.stateName!=""?b.stateName:o;h=b.countryCode!=""?b.countryCode:j;b=b.countryName!=""?b.countryName:
q;j=true;for(n=0;n<c.length;n++)if(c[n].iata==f){j=false;break}j&&this._addSuggestion(c,4,f,i,l,e,g,h,b)}else if(i==="+"||i==="-"){n=l;e=r;g=o;if(i=="+"){e=a.indexOf(",",h+5)+1;b=this._getCityName(m,e);n=b.name;e=b.stateCode!=""?b.stateCode:r;g=b.stateName!=""?b.stateName:o}i=this._getNbOfIATAAirportsInMultiCity(a,h);if(b=i!==0){this._addSuggestion(c,7,f,l,n,e,g,j,q);this._addSuggestion(c,2,f,l,n,e,g,j,q)}else this._addSuggestion(c,5,f,l,n,e,g,j,q);if(b)for(n=0;n<i;n++){p=a.indexOf("#",h)+1;v=a.substr(p,
3);p+=5;b=this._getCityName(m,p);f=b.name;e=b.stateCode!=""?b.stateCode:r;g=b.stateName!=""?b.stateName:o;this._addSuggestion(c,2,v,l,f,e,g,j,q);h=a.indexOf("#",p)}}k++;k=a.indexOf(d,k)}},_getCityName:function(a,d){var c="",b="",e="",g="",h="",f=a.indexOf(",",d);c=a.indexOf("#",d);var i=a.indexOf("[",d),m=a.indexOf("]",d),k=a.indexOf("%",d),j=a.indexOf("~",d);if(f==-1)f=a.length;if(c==-1)c=a.length;if(i==-1)i=a.length;if(m==-1)m=a.length;if(k==-1)k=a.length;if(j==-1)j=a.length;if(c<f)f=c;if(i<f)f=
i;if(m<f)f=m;if(k<f){c=a.substring(d,k);b=a.substring(k+1,k+3);e=a.substring(k+3,f)}else if(j<f){c=a.substring(d,j);g=a.substring(j+1,j+3);h=a.substring(j+3,f)}else c=a.substring(d,f);return{name:c,stateCode:b,stateName:e,countryCode:g,countryName:h}},_getCountryName:function(a,d){var c=a.indexOf("#",d),b=a.indexOf("]",d);if(c==-1)c=a.length;if(b==-1)b=a.length;if(b<c)c=b;return a.substring(d,c)},_addSuggestion:function(a,d,c,b,e,g,h,f,i){for(var m=0,k=a.length,j;m<k;m++){j=a[m];if(j.iata==c&&j.type==
d)return}a.push({type:d,iata:c,cityName:b,airportName:e,stateCode:g,stateName:h,countryCode:f,countryName:i})},suggestionToLabel:function(a){return a.cityName?a.cityName+(a.airportName?","+a.airportName:"")+" ("+a.iata+")":a.iata}}})})();
//AISBa0GIBM
//LOGICAL-PATH:aria/resources/handlers/AIRResourcesHandlerBean.js
//AISBa0GIBM
Aria.beanDefinitions({$package:"aria.resources.handlers.AIRResourcesHandlerBean",$description:"Definition of the suggestions used in the AIR resource handler",$namespaces:{base:"aria.widgets.form.AutoCompleteBean",json:"aria.core.JsonTypes"},$beans:{Suggestion:{$type:"base:Suggestion",$description:"A Label-Code suggestion",$properties:{type:{$type:"json:Integer",$description:"Type of airport. 1 for city, 2 for airport",$sample:1},iata:{$type:"json:String",$description:"IATA code for suggestion",$sample:"CDG",
$mandatory:true},cityName:{$type:"json:String",$description:"City name for this airport",$sample:"Paris"},airportName:{$type:"json:String",$description:"Name of airport",$sample:"Charles de Gaulle"},stateCode:{$type:"json:String",$description:"Code for the state"},stateName:{$type:"json:String",$description:"Name of the state"},countryCode:{$type:"json:String",$description:"Code for the country",$sample:"FR"},countryName:{$type:"json:String",$description:"Name of the country for this airport",$sample:"France"}}}}});