/*
 * Copyright Amadeus
 */
//***MULTI-PART
//AISBa0GIBM
//LOGICAL-PATH:aria/resources/handlers/CitiesResourcesHandler.js
//AISBa0GIBM
(function(){var n,o,l;Aria.classDefinition({$classpath:"aria.resources.handlers.CitiesResourcesHandler",$dependencies:["aria.core.DownloadMgr","aria.utils.String","aria.resources.handlers.CitiesResourcesHandlerBean"],$constructor:function(){this.threshold=3},$statics:{SUGGESTION_BEAN:"aria.resources.handlers.CitiesResourcesHandlerBean.Suggestion",LATIN_CHAR_REGEXP:/^[a-z]/i},$onload:function(){n=aria.core.DownloadMgr;o=aria.core.environment.Environment;l=aria.utils.String},$onunload:function(){l=
o=n=null},$prototype:{getSuggestions:function(a,d){var b=false,c;if(a){c=a.charAt(0).toUpperCase();b=true;if(!this.LATIN_CHAR_REGEXP.test(c)){c=c.charCodeAt(0);if(c<128)b=false}}if(b){b=o.getRegion();a=l.stripAccents(a).toLowerCase();c=Aria.FRAMEWORK_RESOURCES+"IATANonIATACities/"+b+"/"+c+".txt";n.loadFile(c,{fn:this._onResourceReceive,scope:this,args:{textEntry:a,callback:d,logicalPath:c}})}else this.$callback(d,null)},getDefaultTemplate:function(){return"aria.widgets.form.list.templates.CitiesList"},
_onResourceReceive:function(a,d){var b=d.textEntry,c=d.callback;if(a.downloadFailed)this.$callback(c,null);else{var e=aria.core.DownloadMgr.getFileContent(d.logicalPath);b=this._getSuggestions(b,e);this.$callback(c,b)}},_getSuggestions:function(a,d){if(a.length<this.threshold)return null;if(d==null)return[];a=decodeURIComponent(a);var b=[];if(a.length<4){var c="#"+a.toUpperCase();this._searchSuggestion(d,c,b,true)}if(a.length==3){c=0;for(var e=b.length;c<e;c++)b[c].exactMatch=true}c=",";e=true;for(var f=
0;f<a.length;f++){if(e){e=false;c+=a.charAt(f).toUpperCase()}else c+=a.charAt(f).toLowerCase();if(a.charAt(f)==" ")e=true}this._searchSuggestion(d,c,b,false);return b},_searchSuggestion:function(a,d,b,c,e,f){var g,h=a;a=l.stripAccents(a);for(f=f?f:a.indexOf(d);f!=-1;){var i=a.lastIndexOf("#",f)+1,m=a.substr(i,3);g=e?e:a.indexOf(",",i)+1;g=this._getCityName(h,g,d,c);if(g.newPosition){this._searchSuggestion(h,d,b,c,g.newPosition,f);break}else if(e)e=null;g=g.name;var j=a.lastIndexOf("[",f)+1,r=a.substr(j,
2),s=this._getCountryName(h,j+2),k=a.lastIndexOf("]",f)+1,p="",q="";if(k!=-1&&k>j){p=a.substr(k,2);j=a.indexOf("#",k);q=a.substring(k+2,j)}i+=3;a.charAt(i)==="("&&this._addSuggestion(b,m,g,p,q,r,s);f++;f=a.indexOf(d,f)}},_getCityName:function(a,d,b,c){var e="";if(!c)var f=b.slice(1,b.length);b=a.indexOf(",",d);e=a.indexOf("#",d);var g=a.indexOf("[",d),h=a.indexOf("]",d);if(b==-1)b=a.length;if(e==-1)e=a.length;if(g==-1)g=a.length;if(h==-1)h=a.length;if(e<b)b=e;if(g<b)b=g;if(h<b)b=h;e=a.substring(d,
b);if(c)return{name:e};if(e.indexOf(f)===0)return{name:e};return{newPosition:b+1}},_getCountryName:function(a,d){var b=a.indexOf("#",d),c=a.indexOf("]",d);if(b==-1)b=a.length;if(c==-1)c=a.length;if(c<b)b=c;return a.substring(d,b)},_addSuggestion:function(a,d,b,c,e,f,g){for(var h=0,i=a.length,m;h<i;h++){m=a[h];if(m.iata==d)return}a.push({iata:d,cityName:b,stateCode:c,stateName:e,countryCode:f,countryName:g})},suggestionToLabel:function(a){return a.cityName?a.cityName+" ("+a.iata+")":a.iata}}})})();
//AISBa0GIBM
//LOGICAL-PATH:aria/resources/handlers/CitiesResourcesHandlerBean.js
//AISBa0GIBM
Aria.beanDefinitions({$package:"aria.resources.handlers.CitiesResourcesHandlerBean",$description:"Definition of the suggestions used in the Cities resource handler",$namespaces:{base:"aria.widgets.form.AutoCompleteBean",json:"aria.core.JsonTypes"},$beans:{Suggestion:{$type:"base:Suggestion",$description:"A Label-Code suggestion",$properties:{iata:{$type:"json:String",$description:"IATA code for suggestion",$sample:"CDG",$mandatory:true},cityName:{$type:"json:String",$description:"City name",$sample:"Paris"},
stateCode:{$type:"json:String",$description:"Code for the state"},stateName:{$type:"json:String",$description:"Name of the state"},countryCode:{$type:"json:String",$description:"Code for the country",$sample:"FR"},countryName:{$type:"json:String",$description:"Name of the country for this city",$sample:"France"}}}}});